defaults:
  - general: general
#  - override hydra/hydra_logging: colorlog
#  - override hydra/job_logging: colorlog


data_params:
  input_train_data_path: "/kaggle/working/train/train"
#  input_train_data_path: "/Users/vladislavgadzihanov/PycharmProjects/cv_contest/data/vk_made_ocr/train/train"
  input_val_data_path: "/kaggle/working/test/test"
#  input_val_data_path: "/Users/vladislavgadzihanov/PycharmProjects/cv_contest/data/vk_made_ocr/test/test"
  input_targets_path: "/kaggle/working/cv_contest/data/vk_made_ocr/train_labels_no_nan.csv"
#  input_targets_path: "/Users/vladislavgadzihanov/PycharmProjects/cv_contest/data/vk_made_ocr/train_labels_no_nan.csv"
  input_rotation_train_path: "/kaggle/working/cv_contest/inference_predictions_train.csv"
  input_rotation_val_path: "/kaggle/working/cv_contest/inference_predictions_test.csv"

  output_model_path: "/kaggle/working/ocr_crnn_resnet18_gru.pth"
  output_test_metrics_path: "/kaggle/working/test_metrics.json"
  output_test_predictions_path: "/kaggle/working/test_predictions.csv"
  output_val_predictions_path: "/kaggle/working/val_predictions.csv"
  output_encoder_path: "/kaggle/working/label_encoder.joblib"

  test_size: 0.05
  random_state: ${general.random_state}

model_params:
  resize:
    - 64
    - 320
  cnn_output_len: 100
  rnn_hidden_size: 512
  rnn_num_layers: 2
  rnn_dropout: 0.0
  rnn_bidirectional: true

training_params:
  epochs_num: 1
  train_batch_size: 256
  test_batch_size: 512
  val_batch_size: 512
  learning_rate: 5e-4
  factor: 0.9
  patience: 2
  device: "cuda"
  num_workers: 2
  idx_to_angle:
    0: 0
    1: 270
    2: 180
    3: 90



hydra:
  run:
    dir: ../artifacts/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../artifacts/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
