defaults:
  - general: general
#  - override hydra/hydra_logging: colorlog
#  - override hydra/job_logging: colorlog

data_params:
  input_data_path: "/kaggle/working/all_ocr_dataset"
#  input_train_data_path: "/Users/vladislavgadzihanov/PycharmProjects/cv_contest/data/vk_made_ocr/train/train"

  output_model_path: "/kaggle/working/rotation_model_resnet18.pth"
  output_metrics_path: "/kaggle/working/metrics.json"
  output_predictions_path: "/kaggle/working/predictions.csv"

  test_size: 0.05
  random_state: ${general.random_state}

aug_params:
  resize:
    - 256
    - 256

model_params:
  num_classes: 4

training_params:
  epochs_num: 10
  train_batch_size: 64
  test_batch_size: 64
  learning_rate: 5e-4
  factor: 0.9
  patience: 2
  device: "cuda"
  num_workers: 2

hydra:
  run:
    dir: ../artifacts/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../artifacts/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
